source:      .
destination: ./_site
includes:    ./_includes

highlighter: pygments
markdown:    rdiscount
permalink:   /:title

baseurl: http://seanfisher.co/
title: "Sean Fisher"
description: "Sean Fisher is a full stack developer from New York City. Specialties include WordPress, PHP, Laravel, web design and custom application development and design. Works with businesses to create incredible web applications."
root_desc: "Sean Fisher"

rdiscount:
  extensions: []

paginate: 10
paginate_path: blog/:num

exclude: ['README', 'Gruntfile.coffee', 'less', 'css/screen.css']
