source:      .
destination: ./_site
includes:    ./_includes

highlighter: pygments
permalink:   /:title

baseurl: http://seanfisher.co/
title: "Sean Fisher - Software Developer from New York City"
description: "Sean Fisher is a full stack software developer from New York City. Specialties include WordPress, PHP, Laravel, WordPress VIP, web design and custom application development. Works with businesses to create incredible web applications."
root_desc: "Sean Fisher"

rdiscount:
  extensions: []

exclude: ['README', 'Gruntfile.coffee', 'less', 'css/screen.css']
