source:      .
destination: ./_site
includes:    ./_includes

highlighter: pygments
markdown:    rdiscount
permalink:   /:title

baseurl: http://seanfisher.co
#base_url: /
title: "Sean Fisher"
description: "Sean Fisher (srtfisher) is full stack developer from New York City. Sean works to build web applications that are beautiful and useable. Provides services to businesses to improve profits and performance."
root_desc: "Sean Fisher"

rdiscount:
  extensions: []

paginate: 10
paginate_path: blog/:num

exclude: ['README', 'Gruntfile.js', 'less']
